forum/urls.py
from django.urls import path
from forum.views import HomeView, QuestionDetailView, QuestionCreateView, QuestionUpdateView, QuestionDeleteView, question_detail



app_name = 'forum'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('question/<int:pk>/', QuestionDetailView.as_view(), name='question-detail'),
    path('ask/', QuestionCreateView.as_view(), name='question-add'),
    path('question/<int:pk>/edit/', QuestionUpdateView.as_view(), name = 'question-edit'),
    path('question/<int:pk>/delete/',QuestionDeleteView.as_view(), name='question-delete' ),
    # path('answer/', AnswerCreateView.as_view(), name='answer-add'),
    path('<int:pk>/', question_detail, name='question-detail')
]

stacktest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum.urls')),
    path('', include('users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import LogoutView, loginView, RegisterView,ProfileView
app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(), name= 'auth-logout' ),
    path('login/', loginView.as_view(), name='auth-login'),
    path('signup/', RegisterView.as_view(), name='auth-signup'),
    path('profile/', ProfileView.as_view(), name='auth-profile')
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel = 'stylesheet' href = {% static 'static/style.css' %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'forum:home' %}">stackoverflow</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'forum:home' %}">Home</a>
              </li>
            </ul>
            <div class="d-flex justify-content-between">
              <div>
                <form action="{% url 'forum:home' %}" class="d-flex" role="search">
                    {% comment %} {{form.q}} {% endcomment %}
                 <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search" value="{% if form.q.value %}{{ form.q.value }}{% endif %}"> 
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div> 
              <div class="text-white ms-3 dropdown">
                {% if request.user.is_authenticated %}
                    <a href = "{% url 'users:auth-profile' %}"><img width="30" 
                        src="{{ request.user.profile.icon.url }}"
                        class="rounded-circle"
                        alt="{{ request.user.username }}-picture"> </a> {{ request.user.username }}
                      <a class="btn btn-danger ms-3" href="{% url 'users:auth-logout' %}">Logout</a>
                {% else %}
                    <a class="btn btn-primary ms-3" href="{% url 'users:auth-login' %}">Login</a>
                    <a class="btn btn-success ms-3" href="{% url 'users:auth-signup' %}">Sign up</a>
                {% endif %}
        </div>
    </nav>
    {% block content %}
    
    
    {% endblock content %}
</body>
</html>