forum/urls.py
from django.urls import path
from forum.views import HomeView, QuestionDetailView, QuestionCreateView, QuestionUpdateView, QuestionDeleteView, question_detail



app_name = 'forum'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('question/<int:pk>/', QuestionDetailView.as_view(), name='question-detail'),
    path('ask/', QuestionCreateView.as_view(), name='question-add'),
    path('question/<int:pk>/edit/', QuestionUpdateView.as_view(), name = 'question-edit'),
    path('question/<int:pk>/delete/',QuestionDeleteView.as_view(), name='question-delete' ),
    # path('answer/', AnswerCreateView.as_view(), name='answer-add'),
    path('<int:pk>/', question_detail, name='question-detail')
]

stacktest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum.urls')),
    path('', include('users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

forum/models.py
from django.db import models
from users.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.


class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    text = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    modify_time = models. DateTimeField(auto_now=True)
    views = models.PositiveBigIntegerField(default=0, blank=True)
    tags = TaggableManager()

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse('forum:question-detail', kwargs={'pk': self.pk})
    
    class Meta:
        ordering = ['-create_time']

class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    text = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    

    

forum/forms.py
from django import forms
from forum.models import Question, Answer
from django.shortcuts import render, redirect,get_object_or_404
from django.urls import reverse_lazy
from django.forms import ModelMultipleChoiceField

class QuestionCreateForm(forms.ModelForm):
        
    class Meta:
        model = Question
        fields = ['title', 'text', 'tags']



class SearchForm(forms.Form):
    q = forms.CharField(max_length=120, widget=forms.TextInput(attrs={
                                        'type': "search",
                                        'class':"form-control me-2",
                                        'placeholder': "search"
    }))


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['text']

        
    

forum/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect,get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from forum.models import Question, Answer
from forum.forms import QuestionCreateForm, SearchForm, AnswerForm
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from forum.forms import AnswerForm

# Create your views here.

class HomeView(ListView):
    model = Question
    template_name = 'forum/question_list.html'
    paginate_by = 6
    



    def get_queryset(self):
        input_text = self.request.GET.get('q', '') 
        if input_text.startswith('@'):
            # if input_text.startswith('user:'):
            #     parts = input_text.split(':')
            return Question.objects.filter(user__username__icontains=input_text[1])
        elif input_text.startswith('[') and input_text.endswith(']'):
            return Question.objects.filter(tag__name__icontains=input_text[1:-1])

        return Question.objects.filter(title__icontains=input_text)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = SearchForm(self.request.GET)
        return context


class QuestionDetailView(DetailView):
    model = Question
    template_name = 'forum/question_detail.html'

    def get(self, request, *args, **kwargs):
        self.object: Question = self.get_object()
        self.object.views += 1
        self.object.save()
        context = self.get_context_data(object = self.object)
        return self.render_to_response(context)

# def create_question_view(request):
    # question = Question(
    #       user_id = request.GET.get('user'),
    #       title = request.GET.get('title'),
    #       text = request.GET.get('text'),
    #       views = request.GET.get('views'),
    # )
  
    # question.save()
    # if request.method == 'GET':
    #     return render(
    #         request, 
    #         'forum/question_add.html', 
    #         {
    #             'form': QuestionCreateForm()
    #         }
    #      )
    # else:
    #     form = QuestionCreateForm(request.POST)
    #     if form.is_valid:
    #         form.save()
    #         return redirect('forum:home')

    #     return render(
    #         request, 
    #         'forum/question_add.html', 
    #         {
    #             'form': form
    #         }
    #      )

class QuestionCreateView(LoginRequiredMixin, CreateView):
    model = Question
    
    form_class = QuestionCreateForm
    
    success_url = reverse_lazy('forum:home')

    def form_valid(self, form):
        self.object: Question = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)



    template_name = 'forum/question_add.html'

class StaffRequiredMixin:
     def get_queryset(self):
        if self.request.user.is_staff:
            return Question.objects.all()
        return Question.objects.filter(user = self.request.user)


class QuestionUpdateView(StaffRequiredMixin,LoginRequiredMixin, UpdateView):
    model = Question
    fields = ['title', 'text']
    template_name = 'forum/question_edit.html'


class QuestionDeleteView(StaffRequiredMixin,LoginRequiredMixin, DeleteView):
    model = Question
    template_name = 'forum/question_confirm_delete.html'
    fields = ['title', 'text', 'tags']
    success_url = reverse_lazy('forum:home')
    # def get_queryset(self):
    #     if self.request.user.is_staff:
    #         return Question.objects.all()
    #     return Question.objects.filter(user = self.request.user)

    

# class AnswerCreateView(LoginRequiredMixin, CreateView):
#     model = Answer
#     fields = ['text']
#     template_name = 'forum/answer_add.html'

    
# we use this form if we want not to use all the fields of database(models), e make the validation

    # def form_valid(self, form):
    #     self.object: Answer = form.save(commit=False)
    #     self.object.user = self.request.user
    #     question = get_object_or_404(Question,pk=self.request.GET.get('question')) 
    #     self.object.question = question
    #     return super().form_valid(form)

    # def get_success_url(self):
    #     return reverse_lazy('forum:question-detail', kwargs = {'pk':self.object.question.pk}) # how to make dynamic reverse lazy
    
@login_required
def question_detail(request, pk):
    question = get_object_or_404(Question, pk=pk)
    answer = Answer(user=request.user, question=question)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save()
            return redirect(question)
    else:
        form = AnswerForm(instance=answer)
    return render(request, 'forum/question_detail.html', {'question': question, 'form': form})
  

    

templates/forum/question_add.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h2>Ask a public question</h2>



    <div class="bg-dark shadow-lg w-50 rounded p-5 text-white">
        <form method ='POST'>
            {% csrf_token %}
            {{ form|crispy }}
            {#{{form.as_p}}#}
            <button class="btn btn-primary shadow-lg">Ask</button>
        </form>
    </div>
</div>

{% endblock content %}

templates/forum/question_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="position-absolute top-50 start-50 translate-middle text-center">
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete?</p>
        {{form}}
        <a href="{{ object.get_absolute_url }}" class="btn btn-success" type="submit">Go Back</a>
        <button class="btn btn-danger" type="submit">Delete</button>
    </form>

</div>

{% endblock content %}

templates/forum/question_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid w-75">
    <div>
        <div class="d-flex justify-content-between align-items-center">
            <h1>{{ question.title }}</h1>
            <div class="btn-group" role="group" >
                {% if question.user == request.user %}
                    <a href="{% url 'forum:question-edit' question.id %}" class="btn btn-primary">Edit</a>
                    <a href="{% url 'forum:question-delete' question.id %}" class="btn btn-danger">Delete</a>
                {% endif %}
            </div>
        </div>
        <p class="text-break">
            {{ question.text }}
        </p>
        <div class="answer-list">
            {% for answer in question.answers.all %}
                <div id="answer-{{ answer.pk }}">
                    <h3> {{ answer.user }} &mdash; {{ answer.create_time|timesince }}</h3>
                    <p>{{ answer.text }}</p>
                </div>
            {% endfor %}
            <div> 
                <form method="POST" enctype="multipart/form-data">
                    {% comment %} {{ answer_form.as_p }} {% endcomment %}
                    <div class="form-floating">

                    {{ form.as_p }}
                    {% csrf_token %}
                
                    <button class="btn btn-success">Answer</button>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}

{% comment %} {% url 'forum:answer-add'%}?question={{question.pk}}"  {% endcomment %}

templates/forum/question_edit.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div>
    <form method ='POST'>
        {% csrf_token %}
        {{form|crispy}}
        <button class="btn btn-primary shadow-lg">Edit</button>
    </form>
</div>

{% endblock content %}

templates/forum/question_list.html
{% extends 'base.html' %}

{% block content %}

<div class="mt-3 container">
    <div class="d-flex justify-content-between border-bottom pb-3 mb-3 align-items-center">
        <h2>All Questions</h2>
        <a href="{% url 'forum:question-add' %}" class="btn btn-primary shadow-lg">Ask Question</a>
    </div>
    <div>
        {% for question in question_list %}
        <div class="row border-bottom mb-3" id="question-{{ question.id }}">
            <div class="col d-flex flex-column justify-content-center text-end">
                {# <span>0 votes</span> #}
                <span>{{ question.answers.all|length }} answers</span>
                <span>{{ question.views }} views </span>
            </div>
            <div class="col-10">
                <h3><a href="{% url 'forum:question-detail' question.id %}">{{ question.title }}</a></h3> 
                {#<h3><a href="{{ question.get_absolute_url }}">{{ question.title }}</a></h3>#}
                <p class="text-break">
                    {{ question.text|slice:255 }}
                    {% if question.text|length > 255 %}
                        ...
                    {% endif %}
                </p>
                <div class="d-flex justify-content-between">
                    <div>
                        {% for tag in question.tags.all %}
                            <a href="#" class="badge bg-primary">{{ tag }}</a>
                        {% endfor %}
                    </div>
                    <div>
                        <p>
                            {{ question.user.username }} &mdash; asked {{ question.create_time|timesince }} ago
                        </p>
                    </div>
                </div>
            </div>
        </div>
        
    {% endfor %}
    <div class="pagination text-center justify-content-center">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1{% if form.q.value %}&q={{ form.q.value }} {% endif %}" class="btn btn-primary">&#10094;&#10094;</a>
            <a href="?page={{ page_obj.previous_page_number }}{% if form.q.value %}&q={{ form.q.value }} {% endif %}" class="btn btn-primary">&#10094;</a>
        {% endif %}

        <span class="current btn btn-primary btn-disabled">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}{% if form.q.value %}&q={{ form.q.value }} {% endif %}"class="btn btn-primary">&#10095;</a>
            <a href="?page={{ page_obj.paginator.num_pages }}{% if form.q.value %}&q={{ form.q.value }} {% endif %}" class="btn btn-primary">&#10095;&#10095;</a>
        {% endif %}
    </span>
</div>
{% endblock content %}